### ISSUE TITLE
Debian Buster / Installscript not working

### ISSUE THREAD

**Issue by scysys** [openbroadcaster/observer#16]
<img width="1052" alt="Bildschirmfoto 2021-04-01 um 17 23 39" src="https://user-images.githubusercontent.com/1695531/113316849-11f51900-930f-11eb-889f-592113a3be33.png">

**Comment by puntopunto** [comment]
I think it's normal.
Too new version of OS.
You need to find missed packages and install it from older repos or manually.
After installation you need to fix how JS works, because it's broken on new OS'es too ;)
(But, there is no major differences with ABI layer in old and new OS'es, so old php/js WILL work on modern OS with minimal fixing).
Installation scrip needs to be rewritten, for my home-lab installation i did this and... Now I fixing JS part of project)

I will finish and check the functionality of my version of the installation script within the next couple of weeks, if everything works well and no one offers a better option than mine (I'm a lamer, I write bad code, my work can only be used from complete hopelessness), I will send a pull-request to the main repository.

**Comment by Sturmey66** [comment]
I fixed most of it by adding this repository

`sudo add-apt-repository ppa:ondrej/php`

**Comment by radiorob** [comment]
https://gitcoin.co/issue/openbroadcaster/observer/15/100026997
