### ISSUE TITLE
Fresh install on Ubuntu Server 20.04 - Can't login

### ISSUE THREAD

**Issue by XanderCodes** [openbroadcaster/observer#161]
Hi there.

I have just installed observer on a fresh install of Ubuntu 20.04 using the ob.installer.sh script.

The installation completes, and spits out an admin password and database login - but if I browse to the page and try to use the password with the username "admin", the page refreshes with no error message. If the wrong password is entered I get the "incorrect password" message.

Also, I see some of the documentation pointing to tools in the /var/www/observer/tools/cli folder, but the cli folder doesn't seem to exist.

Any help is greatly appreciated. Thanks.

**Comment by triplectwc** [comment]
I was able to get to the login screen as well, but it's pretty much having the same behavior. Also, I'm honestly not understanding how it's expecting me to use the CLI tools when that folder doesn't seem to exist (so same issue here) or even be included in the GitHub repo for that matter. Anyone have any ideas why the CLI folder (/var/www/observer/tools/cli) and its contents wouldn't be there? My installation process went smoothly otherwise with no error messages, so no complaints otherwise.

**Comment by radiorob** [comment]
CLI tool is available in 5.3 Branch.  Made a note in Main branch installer.txt until 5.3 becomes main.
