### ISSUE TITLE
Not able to log in Observer after changing network

### ISSUE THREAD

**Issue by decibecca** [openbroadcaster/observer#39]
Observer was originally set up on a first network. Everything was working perfectly. After changing network it was no longer possible to connect to the homepage. The login button no longer reacts. I reconnected the computer to the initial network and everything became functional again.

1. Setup and test Observer login page -> Everything work fine
2. Connect hardware to a new network/router
3. Try to connect to Observer login page
4. Nothing happens

 - OS: Pyrate on Raspberry Pi 3
 - Browser Chrome
 - Version 99.0.4844.74 (Build officiel) (64 bits)

**Comment by Xenarc** [comment]
Hi @decibecca, thanks for raising this issue!
I know it has been a while since you raised this issue, but if you would kindly provide additional logging output, we help narrow down the source of the problem. 

From what it sounds like, the server may be encountering a problem connecting to the database. Also, when you say 'Nothing happens' do you mean that there is an http `204` response, or a blank page, or something different?

**Comment by brookgagnon** [comment]
Closing issue due to lack of reply with more details. If you're still working on this, could you let me know your [Discord](https://discord.com/) username so we can work together to resolve this issue (and fix any associated bugs if applicable)? Or send me a message on Discord - nightwolf#5044
